import 'package:dia_plus/models/glucose_pattern_type.dart';
import 'package:dia_plus/models/insight_severity.dart';

/// Structured insight generated by rule-based pattern detection.
class GlucosePatternInsight {
  const GlucosePatternInsight({
    required this.id,
    required this.type,
    required this.title,
    required this.message,
    required this.severity,
    required this.detectedAt,
    required this.periodLabel,
    required this.supportingCount,
    required this.relevanceLabel,
    required this.recommendedAction,
    this.relatedReadingIds = const [],
    required this.createdAt,
  });

  final String id;
  final GlucosePatternType type;
  final String title;
  final String message;
  final InsightSeverity severity;
  final DateTime detectedAt;
  final String periodLabel;
  final int supportingCount;
  final String relevanceLabel;
  final String recommendedAction;
  final List<String> relatedReadingIds;
  final DateTime createdAt;

  GlucosePatternInsight copyWith({
    String? id,
    GlucosePatternType? type,
    String? title,
    String? message,
    InsightSeverity? severity,
    DateTime? detectedAt,
    String? periodLabel,
    int? supportingCount,
    String? relevanceLabel,
    String? recommendedAction,
    List<String>? relatedReadingIds,
    DateTime? createdAt,
  }) {
    return GlucosePatternInsight(
      id: id ?? this.id,
      type: type ?? this.type,
      title: title ?? this.title,
      message: message ?? this.message,
      severity: severity ?? this.severity,
      detectedAt: detectedAt ?? this.detectedAt,
      periodLabel: periodLabel ?? this.periodLabel,
      supportingCount: supportingCount ?? this.supportingCount,
      relevanceLabel: relevanceLabel ?? this.relevanceLabel,
      recommendedAction: recommendedAction ?? this.recommendedAction,
      relatedReadingIds: relatedReadingIds ?? this.relatedReadingIds,
      createdAt: createdAt ?? this.createdAt,
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'id': id,
      'type': type.name,
      'title': title,
      'message': message,
      'severity': severity.name,
      'detectedAt': detectedAt.toIso8601String(),
      'periodLabel': periodLabel,
      'supportingCount': supportingCount,
      'relevanceLabel': relevanceLabel,
      'recommendedAction': recommendedAction,
      'relatedReadingIds': relatedReadingIds,
      'createdAt': createdAt.toIso8601String(),
    };
  }

  factory GlucosePatternInsight.fromMap(Map<String, dynamic> map) {
    return GlucosePatternInsight(
      id: map['id'] as String,
      type: _parsePatternType(map['type'] as String?),
      title: map['title'] as String? ?? '',
      message: map['message'] as String? ?? '',
      severity: _parseSeverity(map['severity'] as String?),
      detectedAt: _parseDate(map['detectedAt']),
      periodLabel: map['periodLabel'] as String? ?? '',
      supportingCount: (map['supportingCount'] as num?)?.toInt() ?? 0,
      relevanceLabel: map['relevanceLabel'] as String? ?? '',
      recommendedAction: map['recommendedAction'] as String? ?? '',
      relatedReadingIds:
          (map['relatedReadingIds'] as List<dynamic>?)
              ?.map((item) => item.toString())
              .toList() ??
          const [],
      createdAt: _parseDate(map['createdAt']),
    );
  }

  static GlucosePatternType _parsePatternType(String? value) {
    if (value == null) {
      return GlucosePatternType.unstableReadings;
    }
    for (final item in GlucosePatternType.values) {
      if (item.name == value) {
        return item;
      }
    }
    return GlucosePatternType.unstableReadings;
  }

  static InsightSeverity _parseSeverity(String? value) {
    if (value == null) {
      return InsightSeverity.info;
    }
    for (final item in InsightSeverity.values) {
      if (item.name == value) {
        return item;
      }
    }
    return InsightSeverity.info;
  }

  static DateTime _parseDate(dynamic value) {
    if (value is String) {
      return DateTime.tryParse(value) ?? DateTime.now();
    }
    return DateTime.now();
  }
}
