// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDM3xd7boFM7RNrO8GmktpUj0IINWR-l94',
    appId: '1:284015189329:web:a7daf89f25b454717b8770',
    messagingSenderId: '284015189329',
    projectId: 'dia-plus-7c78c',
    authDomain: 'dia-plus-7c78c.firebaseapp.com',
    storageBucket: 'dia-plus-7c78c.firebasestorage.app',
    measurementId: 'G-E56EY37YR5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALzg3GX-CjSIhXQTD1ugMR_9aDItiBIyc',
    appId: '1:284015189329:android:d0b7c50ec1df95ee7b8770',
    messagingSenderId: '284015189329',
    projectId: 'dia-plus-7c78c',
    storageBucket: 'dia-plus-7c78c.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKVXlEiuVJ4WZ6T-8NCJUeAT5xBe4KsE8',
    appId: '1:284015189329:ios:607fe26ea81ecbed7b8770',
    messagingSenderId: '284015189329',
    projectId: 'dia-plus-7c78c',
    storageBucket: 'dia-plus-7c78c.firebasestorage.app',
    androidClientId: '284015189329-0g8mg1mj3htap4fivlrpmtfsm2ccs6h5.apps.googleusercontent.com',
    iosClientId: '284015189329-4aenivlvn5ntrchq8t45s85n617e01eg.apps.googleusercontent.com',
    iosBundleId: 'com.example.diaPlus',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKVXlEiuVJ4WZ6T-8NCJUeAT5xBe4KsE8',
    appId: '1:284015189329:ios:607fe26ea81ecbed7b8770',
    messagingSenderId: '284015189329',
    projectId: 'dia-plus-7c78c',
    storageBucket: 'dia-plus-7c78c.firebasestorage.app',
    androidClientId: '284015189329-0g8mg1mj3htap4fivlrpmtfsm2ccs6h5.apps.googleusercontent.com',
    iosClientId: '284015189329-4aenivlvn5ntrchq8t45s85n617e01eg.apps.googleusercontent.com',
    iosBundleId: 'com.example.diaPlus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLRtzJ1GM2BpRMVDF_Q7tb5Q2Ab_Y55ps',
    appId: '1:284015189329:web:b667c4975ae603af7b8770',
    messagingSenderId: '284015189329',
    projectId: 'dia-plus-7c78c',
    authDomain: 'dia-plus-7c78c.firebaseapp.com',
    storageBucket: 'dia-plus-7c78c.firebasestorage.app',
    measurementId: 'G-KD9Q57HH4F',
  );

}